# Grafana Datasource Configuration for FaceSocial AI Services
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    basicAuth: false
    withCredentials: false
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      cacheLevel: 'High'
      disableMetricsLookup: false
      customQueryParameters: ''
      timeInterval: "15s"
    secureJsonFields: {}
    version: 1
    readOnly: false

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: facesocial_ai
    user: facesocial
    secureJsonData:
      password: password123
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    editable: true
    version: 1
    readOnly: false
